services:
  - type: web
    name: studio-booking
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /docs
    envVars:
      - key: APP_ENV
        value: prod
      - key: PUBLIC_BASE_URL
        value: https://studio-booking.onrender.com
      - key: SECRET_KEY
        sync: false
      - key: JWT_EXPIRES_MIN
        value: "1440"
      - key: DB_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: MANAGER_EMAILS
        sync: false
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1